spring:
  application:
    name: mxx-blog
  resources:
    static-locations: classpath:/static/
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/blog-mxx?serverTimezone=UTC
    username: root
    password: 123456


