spring:
  application:
    name: mxx-blog

  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/blog-mxx?serverTimezone=UTC
    username: root
    password: 123456


#thymeleaf start
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    encoding: UTF-8
    cache: false
    mode: HTML
    servlet:
      content-type: text/html
#thymeleaf end









